spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33066/tnovel?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000

  jackson:
    time-zone: Asia/Seoul

  jpa:
    hibernate:
      ddl-auto: none   # 개발용: 스키마 자동 생성
    properties:
      hibernate:
        format_sql: true
    show-sql: false
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: "${OAUTH_REDIRECT_BASE_URL}/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000

encrypt:
  secret-key: ${ENCRYPT_SECRET_KEY}

server:
  port: 8080

portone:
  base-url: https://api.iamport.kr
  rest:
    api-key: ${PORTONE_REST_API_KEY}
    api-secret: ${PORTONE_REST_API_SECRET}

file:
  upload-dir: src/main/resources/static/uploads/posts


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
